server:
  port: 8085

spring:
  application:
    name: notification-service

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service
      auto-offset-reset: latest # Default Behavior (Read from latest)
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

#  mail:
#    host: smtp.example.com
#    port: 587
#    username: no-reply@example.com
#    password: change-me
#    properties:
#      mail.smtp.auth: true
#      mail.smtp.starttls.enable: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    root: INFO
    com.skillance: INFO

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

