spring:
  application:
    name: gig-service

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka/
#      defaultZone: http://localhost:8761/eureka/
