server:
  port: 8084

spring:
  config:
    activate:
      on-profile: prod

  application:
    name: PAYMENT-SERVICE

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus   # expose actuator endpoints
  endpoint:
    health:
      show-details: always
