server:
  port: 8083

spring:
  config:
    activate:
      on-profile: prod

  application:
    name: ORDER-SERVICE

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus   # expose actuator endpoints
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      GIG-SERVICE:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 2s
      PAYMENT-SERVICE:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 2s

  retry:
    instances:
      GIG-SERVICE:
        maxAttempts: 3
        waitDuration: 2s
      PAYMENT-SERVICE:
        maxAttempts: 3
        waitDuration: 2s