spring:
  datasource:
    url: jdbc:postgresql://postgres-order:5432/skillance-orders
    username: lakshitha
    password: lakshitha12
    driver-class-name: org.postgresql.Driver

eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka/
