name: Service Discovery CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-test-docker:
    name: Build, Test & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Build with Maven
      - name: Build with Maven
        run: mvn -B clean compile --file service-discovery/pom.xml

      # Step 4: Run Tests
      - name: Run Tests
        run: mvn -B test --file service-discovery/pom.xml

      # Step 5: Package JAR
      - name: Package JAR
        run: mvn -B package --file service-discovery/pom.xml

      # Step 6:1: Log in to Docker Hub
#      - name: Log in to Docker Hub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
